### ISSUE TITLE
Windows beta testing

### ISSUE THREAD

**Issue by nebbian** [nebbian/RoboxSlicerExtension#30]
I'd appreciate it if anyone who tries to get this working in Windows could post their experiences here.

I've gotten it working with a heavily doctored system, and am wondering how easy it is to get going on a normal windows install.

Try installing using the instructions in the README file, and post here how you go.

**Comment by 24c** [comment]
OK guys, trying to get started on this for you, but failing at first hurdle...obviously Automaker is in Program files as is Slic3r, but "Robox-extensions-installer" goes where? On the Mac it's in the CEL folder within Applications, but I cannot get it to open using the cmd line...if you're a novice where should we start? Usually everything starts in the Downloads folder.

**Comment by nebbian** [comment]
Perhaps something like:
"C:\Program Files\CEL\AutoMaker\java\bin\java.exe" -jar robox-extensions-installer.jar
might work?

**Comment by nebbian** [comment]
I don't think that it matters where the Robox-extensions-installer goes.  Did you try double clicking the file "Robox-Windows launch Installer here.cmd"?

**Comment by 24c** [comment]
Yes, and it wants to open with Internet Explorer or Visual Studio :/

**Comment by 24c** [comment]
but if you double click "Robox-Windows launch installer here" something is happening.

**Comment by 24c** [comment]
Something has happened, but Automaker is not responding past the Layout page, I cannot add a model, but have drag and dropped an STL file onto the bed, but by going back to the Status tab, I could shift to the Layout page, and then this...
![screen shot 2017-08-05 at 20 02 00](https://user-images.githubusercontent.com/29804537/28997982-1fcb958a-7a19-11e7-9a9e-0890f4c249c8.png)

**Comment by 24c** [comment]
![screen shot 2017-08-05 at 20 03 36](https://user-images.githubusercontent.com/29804537/28997989-351d6c9c-7a19-11e7-9f78-111e257e4ca6.png)

**Comment by 24c** [comment]
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	CuraEngine.exe
  Application Version:	0.0.0.0
  Application Timestamp:	598016f5
  Fault Module Name:	libmingwex-0.dll
  Fault Module Version:	6.3.9600.18696
  Fault Module Timestamp:	5915ecd6
  Exception Code:	c0000135
  Exception Offset:	0009d4c2
  OS Version:	6.3.9600.2.0.0.256.48
  Locale ID:	2057
  Additional Information 1:	1abe
  Additional Information 2:	1abee00edb3fc1158f9ad6f44f0f6be8
  Additional Information 3:	1abe
  Additional Information 4:	1abee00edb3fc1158f9ad6f44f0f6be8

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-GB\erofflps.txt

**Comment by 24c** [comment]
Is this what the Cura folder should look like or have I got legacy stuff in here?
![screen shot 2017-08-05 at 20 06 57](https://user-images.githubusercontent.com/29804537/28998030-c7b5498a-7a19-11e7-84e7-e5c2e66912d6.png)

**Comment by nebbian** [comment]
Gosh.  That's a substantial crash.  What version of windows do you have?

**Comment by 24c** [comment]
Windows 8.1 on Parallels using the iMac

**Comment by nebbian** [comment]
Hmmm.  I'm using Windows 10 on VirtualBox on a mac.

![screen shot 2017-08-06 at 3 12](https://user-images.githubusercontent.com/489642/28998097-c714b2d6-7a55-11e7-86c9-c19be1af0f76.png)

![screen shot 2017-08-06 at 3 13 1](https://user-images.githubusercontent.com/489642/28998105-ee9b0b20-7a55-11e7-8a2f-0dcbe73623c9.png)
![screen shot 2017-08-06 at 3 13](https://user-images.githubusercontent.com/489642/28998106-f03f84d8-7a55-11e7-8185-eac19b8a9272.png)
![screen shot 2017-08-06 at 3 15 1](https://user-images.githubusercontent.com/489642/28998108-f473f336-7a55-11e7-90b6-91b6092d7a5d.png)
![screen shot 2017-08-06 at 3 15](https://user-images.githubusercontent.com/489642/28998110-f9130cb0-7a55-11e7-9073-25c800e3209d.png)
![screen shot 2017-08-06 at 3 16 1](https://user-images.githubusercontent.com/489642/28998112-ff20c5de-7a55-11e7-934e-7b648b581d5b.png)

**Comment by 24c** [comment]
Hmmm, not getting that far, cleaned up the Cura folder... and still got this

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	CuraEngine.exe.exe
  Application Version:	0.0.0.0
  Application Timestamp:	598016f5
  Fault Module Name:	libmingwex-0.dll
  Fault Module Version:	6.3.9600.18696
  Fault Module Timestamp:	5915ecd6
  Exception Code:	c0000135
  Exception Offset:	0009d4c2
  OS Version:	6.3.9600.2.0.0.256.48
  Locale ID:	2057
  Additional Information 1:	1abe
  Additional Information 2:	1abee00edb3fc1158f9ad6f44f0f6be8
  Additional Information 3:	1abe
  Additional Information 4:	1abee00edb3fc1158f9ad6f44f0f6be8

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-GB\erofflps.txt

**Comment by 24c** [comment]
Does this make any sense,?

https://sourceforge.net/p/mingw/news/2017/02/mingwrt-50-and-w32api-50-snapshots-available/

**Comment by 24c** [comment]
![screen shot 2017-08-05 at 20 47 03](https://user-images.githubusercontent.com/29804537/28998329-d27e63aa-7a1f-11e7-991c-e877940ec4ea.png)
If I do the usual renaming trick, AutoMaker calculates the print time, and will work as per normal, so there must be an issue somewhere. :/ Where should "Robox-slicer-flow-1.0-SNAPSHOT" live?

**Comment by 24c** [comment]
revert back and problem is still there, time is stalled at "working"...
![screen shot 2017-08-05 at 20 54 22](https://user-images.githubusercontent.com/29804537/28998346-5421b8ee-7a20-11e7-9082-f19bc49f660d.png)

**Comment by nebbian** [comment]
I've just uploaded a new CuraEngine.exe file, that is statically linked this time.  You can find it here:
https://github.com/nebbian/RoboxSlicerExtension/blob/master/windows%20scripts/CuraEngine.exe
(click "Download").  Give it a go, it appears to work on my Windows 7 VM.

**Comment by nebbian** [comment]
@24c:

> If I do the usual renaming trick, AutoMaker calculates the print time, and will work as per normal, so there must be an issue somewhere. :/ Where should "Robox-slicer-flow-1.0-SNAPSHOT" live?

It should be in C:\Program Files\CEL\Common.

**Comment by 24c** [comment]
OK, I've downloaded the latest version, and double clicked the .cmd file, and everything installed. It doesn't crash now, but neither does it slice either...it just bypasses this mode when you press Make, it queue etc, but doesn't print. I had to rename the slic3r PE, as it had a load of extra characters in the filename, but that still didn't resolve it. Going to download minnow and see if that's what I am doing wrong, but at least it is getting further my iMac running Parallels 12

![screen shot 2017-08-06 at 16 11 20](https://user-images.githubusercontent.com/29804537/29004599-f2191a32-7ac1-11e7-8b1c-dae71d527309.png)

Then it's followed by "Cancelling" bottom left white text on blue bar

**Comment by nebbian** [comment]
Can you post the following files please?
C:\Users\[YOURUSERNAME]\Documents\CEL Robox\PrintJobs\[LATESTPRINTJOB]\slicer_wrapper.log

C:\Users\[YOURUSERNAME]\Documents\CEL Robox\robox_slicer_extension.log

C:\Users\[YOURUSERNAME]\AppData\Roaming\CEL Robox\AutoMaker.log

This might give us some clues.

Also post a screenshot of windows explorer, showing the contents of C:\Program Files\Slic3r

**Comment by 24c** [comment]
OK, Ben, first issue, CEL Robox didn’t install into the Documents folder for some reason, but other stuff for info.


> Can you post the following files please?
> C:\Users[YOURUSERNAME]\Documents\CEL Robox\PrintJobs[LATESTPRINTJOB]\slicer_wrapper.log
> 
> C:\Users[YOURUSERNAME]\Documents\CEL Robox\robox_slicer_extension.log
> 
> C:\Users[YOURUSERNAME]\AppData\Roaming\CEL Robox\AutoMaker.log
> 
> This might give us some clues.
> 
> Also post a screenshot of windows explorer, showing the contents of C:\Program Files\Slic3r
> 



Logfile for Robox-slicer-extension

19:16:53.123 INFO    [java.util.logging.LogManager$RootLogger log] Started robox slicer extension 
19:16:53.127 FINE    [com.roboxing.slicerextension.flow.Arguments process] Invoked with arguments: 
19:16:53.128 FINE    [com.roboxing.slicerextension.flow.Arguments process]   -v 
19:16:53.128 FINE    [com.roboxing.slicerextension.flow.Arguments process]   -p 
19:16:53.128 FINE    [com.roboxing.slicerextension.flow.Arguments process]   -c 
19:16:53.130 FINE    [com.roboxing.slicerextension.flow.Arguments process]   ce712db1b4b74193.roboxprofile 
19:16:53.130 FINE    [com.roboxing.slicerextension.flow.Arguments process]   -o 
19:16:53.130 FINE    [com.roboxing.slicerextension.flow.Arguments process]   ce712db1b4b74193.gcode 
19:16:53.130 FINE    [com.roboxing.slicerextension.flow.Arguments process]   ce712db1b4b74193-0.stl 
19:16:53.130 FINER   [com.roboxing.slicerextension.flow.Arguments process] Argument : -v 
19:16:53.131 FINER   [com.roboxing.slicerextension.flow.Arguments process] Argument : -p 
19:16:53.131 FINER   [com.roboxing.slicerextension.flow.Arguments process] Argument : -c 
19:16:53.131 FINER   [com.roboxing.slicerextension.flow.Arguments process] Argument : -o 
19:16:53.132 FINER   [com.roboxing.slicerextension.flow.Arguments process] Argument : ce712db1b4b74193-0.stl 
19:16:53.133 CONFIG  [com.roboxing.slicerextension.flow.Arguments ensureArgumentsValid] Assumed AM installation dir as C:\Program Files\CEL 
19:16:53.139 FINE    [com.roboxing.slicerextension.flow.Controller process] Selecting Slic3r - current dir contains 'PrintJobs'; L:\Documents\CEL Robox\PrintJobs\ce712db1b4b74193 
19:16:53.143 FINE    [com.roboxing.slicerextension.flow.Controller process] Invoking Slic3r 
19:16:53.143 FINE    [com.roboxing.slicerextension.flow.Slic3r invoke] Invoking Slic3r with args:  
19:16:53.143 FINE    [com.roboxing.slicerextension.flow.Slic3r invoke]   /Applications/Slic3r.app/Contents/MacOS/Slic3r 
19:16:53.144 FINE    [com.roboxing.slicerextension.flow.Slic3r invoke]   --gui 
19:16:53.144 FINE    [com.roboxing.slicerextension.flow.Slic3r invoke]   -o 
19:16:53.144 FINE    [com.roboxing.slicerextension.flow.Slic3r invoke]   L:\Documents\CEL Robox\PrintJobs\ce712db1b4b74193\ce712db1b4b74193.slicer.gcode 
19:16:53.144 FINE    [com.roboxing.slicerextension.flow.Slic3r invoke]   L:\Documents\CEL Robox\PrintJobs\ce712db1b4b74193\ce712db1b4b74193-0.stl 
19:16:53.149 SEVERE  [com.roboxing.slicerextension.flow.Main main] Error processing :  
java.io.IOException: Cannot run program "/Applications/Slic3r.app/Contents/MacOS/Slic3r": CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.roboxing.slicerextension.flow.Slic3r.invoke(Slic3r.java:54)
	at com.roboxing.slicerextension.flow.Controller.process(Controller.java:79)
	at com.roboxing.slicerextension.flow.Main.main(Main.java:67)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 3 more






Hope this helps..
Mike

**Comment by nebbian** [comment]
Well that will never work!  It's trying to call the mac version of Slic3r.  I wonder what version of the robox slicer extension jarfile you're running?  Perhaps try replacing c:/Program Files/CEL/Common/robox-slicer-flow-1.0-SNAPSHOT.jar with this one:
https://github.com/nebbian/RoboxSlicerExtension/blob/master/robox-slicer-flow-1.0-SNAPSHOT.jar

**Comment by natdan** [comment]
Our extension tried to invoke Mac Slic3r not Windows. @nebbian I think we need to update our .jar in github - it might be old version there. If I get time I'll do it - but if I don't post here in next hour - please do maven build and update new version of our jar. It is possible you've done it locally and that's the reason it works for you! :)

**Comment by natdan** [comment]
LOL - we typed at the same time! :)

**Comment by nebbian** [comment]
@natdan, I updated it yesterday :)

**Comment by natdan** [comment]
@24c Installer when run should detect previous installation and allow you to uninstall it and install it again. Maybe you should try that if you haven't already...

**Comment by 24c** [comment]
> Well that will never work! It's trying to call the mac version of Slic3r. I wonder what version of the robox slicer extension jarfile you're running? Perhaps try replacing c:/Program Files/CEL/Common/robox-slicer-flow-1.0-SNAPSHOT.jar with this one:
> 
> 

Interesting, I don’t know why that is, but when I have just put the CEL Robox file in the Documents folder, something is happening



…and that’s all it was, the CEL Robox folder hadn’t installed into the Documents folder, so is this an error in the installer?


Cheers
Mike

**Comment by nebbian** [comment]
@24c is it slicing properly now?  Interested to hear what's going on.  I had to do all manner of trickery to get things to work for me, I've forgotten all the things I did to get it all happening.

From memory I thought that the CEL Robox folder in the Documents was actually created by AutoMaker, I could be wrong though.

**Comment by 24c** [comment]
> @24c <https://github.com/24c> is it slicing properly now? Interested to hear what's going on. I had to do all manner of trickery to get things to work for me, I've forgotten all the things I did to get it all happening.
> 
> From memory I thought that the CEL Robox folder in the Documents was actually created by AutoMaker, I could be wrong though.
> 

Hi again, that’s why I thought I’d have a go. I did uninstall stuff previously, and I used the later update, and it did update @natdan. :)
The problem was definitely the CEL Robox install being in a different place, not sure which is right?

The only other thing that might interest you, is when Slic3r opens as part of the AutoMaker Make sequence, it flashes in the screen briefly, then goes behind AutoMaker window, and flashes in the TaskBar. Obviously clicking on this, brings it to the front…it doesn’t do this in the Mac version

Mike
